// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPrGCLWMZyF8A7qgUdY6KWkpsfpXQ428',
    appId: '1:962712836791:web:5af51e26e239809f0f8b32',
    messagingSenderId: '962712836791',
    projectId: 'shopping-2697a',
    authDomain: 'shopping-2697a.firebaseapp.com',
    storageBucket: 'shopping-2697a.appspot.com',
    measurementId: 'G-1EEZ75TFCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3exbaCjK1eF8ZwDRtU6OxLqcPHeAZ42c',
    appId: '1:962712836791:android:5d666d05df331cad0f8b32',
    messagingSenderId: '962712836791',
    projectId: 'shopping-2697a',
    storageBucket: 'shopping-2697a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBikECUVjEN5nxWjIGuCwksDjF4462AHvo',
    appId: '1:962712836791:ios:8f939bb883f8977c0f8b32',
    messagingSenderId: '962712836791',
    projectId: 'shopping-2697a',
    storageBucket: 'shopping-2697a.appspot.com',
    androidClientId: '962712836791-0brf3ctjgq3gb16g8ffgulkci5epc7d6.apps.googleusercontent.com',
    iosClientId: '962712836791-je2dnqmv5qd94f6j0ov829dd3lk6aa64.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBikECUVjEN5nxWjIGuCwksDjF4462AHvo',
    appId: '1:962712836791:ios:8f939bb883f8977c0f8b32',
    messagingSenderId: '962712836791',
    projectId: 'shopping-2697a',
    storageBucket: 'shopping-2697a.appspot.com',
    androidClientId: '962712836791-0brf3ctjgq3gb16g8ffgulkci5epc7d6.apps.googleusercontent.com',
    iosClientId: '962712836791-je2dnqmv5qd94f6j0ov829dd3lk6aa64.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIPrGCLWMZyF8A7qgUdY6KWkpsfpXQ428',
    appId: '1:962712836791:web:3823a85995525d720f8b32',
    messagingSenderId: '962712836791',
    projectId: 'shopping-2697a',
    authDomain: 'shopping-2697a.firebaseapp.com',
    storageBucket: 'shopping-2697a.appspot.com',
    measurementId: 'G-PFTNHBXLPK',
  );
}
